server:
  port: 8000
spring:
  application:
    name: plant-blog
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://${planet.mysql.ip}:${planet.mysql.port}/${planet.mysql.db}?useUnicode=true&&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${planet.mysql.username}
    password: ${planet.mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${planet.redis.host}
    # Redis服务器端口号
    port: ${planet.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${planet.redis.password}
  # 邮箱配置
  mail:
    host: ${planet.mail.host}
    port: ${planet.mail.port}
    protocol: ${planet.mail.protocol}
    username: ${planet.mail.username}
    password: ${planet.mail.password}
    properties:
      mail:
        smtp:
          socketFactory:
            port: ${planet.mail.port}
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      # swagger新UI所需配置
      matching-strategy: ANT_PATH_MATCHER
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
oss:
  enabled: ${planet.oss.enabled}
  type: ${planet.oss.type}
  endpoint: ${planet.oss.endpoint}
  access-key: ${planet.oss.access-key}
  secret-key: ${planet.oss.secret-key}
  bucket-name: ${planet.oss.bucket-name}
jwt:
  secret: ${planet.jwt.secret}
logging:
  file:
    path: ${planet.log.path}
